# Generated by Django 3.2.3 on 2024-07-02 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_auto_20240701_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(default='default_recipe_image.png', upload_to='recipes/images/', verbose_name='Картинка'),
        ),
    ]
