# Generated by Django 3.2.3 on 2024-07-03 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_alter_recipe_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='short_link',
            field=models.CharField(blank=True, max_length=16, null=True, unique=True, verbose_name='Короткая ссылка'),
        ),
    ]
