# Generated by Django 3.2.3 on 2024-07-12 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20240701_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='default_avatar.png', null=True, upload_to='users/images/', verbose_name='Аватар'),
        ),
    ]
